apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cloud-python
  labels:
    app: cloud-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-python
  template:
    metadata:
      labels:
        app: cloud-python
    spec:
      containers:
      - name: cloud-python
        image: gcr.io/url-shortener-189609/tinche/cloud-python
        ports:
        - containerPort: 8000
        args: ["runbjoern"]
        env:
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloud-python-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloud-python-db-credentials
                key: password
          - name: DJANGO_SETTINGS_MODULE
            value: cloud.settings_prod
        readinessProbe:
          httpGet:
            path: /admin/login/
            port: 8000
        resources:
          requests:
            cpu: "50m"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=url-shortener-189609:us-central1:cloud-python=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir: