apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud-python
spec:
  backend:
    serviceName: cloud-python
    servicePort: 8000
  rules:
  - http:
      paths:
      - path: /static
        backend:
          serviceName: cloud-python-static
          servicePort: 80
      - path: /static/*
        backend:
          serviceName: cloud-python-static
          servicePort: 80